name: check

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.3.0

      - name: Use cached dependencies
        id: cache-opam
        uses: actions/cache@v3
        env:
          opam-cache-name: cache-opam
        with:
          path: ~/.opam
          key: ${{ env.opam-cache-name }}-build-${{ hashFiles('build.sh') }}

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        env:
          llvm-cache-name: cache-llvm
        with:
          path: /opt/llvm-project
          key: ${{ env.llvm-cache-name }}-${{ hashFiles('build.sh') }}

            
      - name: Install dependencies
        run:
          sudo apt-get update && sudo apt-get install -y re2c z3

      - name: Build Optimuzz
        run: ./build.sh
        env:
          LLVM_PATH: /opt/llvm-project/

      - name: Check Instrumentation Build
        run: make -C instrumentation
        env:
          LLVM_PATH: /opt/llvm-project/