name: check

on: [push, pull_request]

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0.0

      - name: Install ocamlformat
        run: opam install ocamlformat.0.26.1

      - name: Check format
        run: |
          eval $(opam env)
          scripts/check-format

      - name: Use cached dependencies
        id: cache-opam
        uses: actions/cache@v3
        env:
          cache-name: cache-opam
        with:
          path: |
            ~/.opam
            ./_opam
          key: ${{ env.cache-name }}-build-${{ hashFiles('build.sh') }}
      
      - name: Install LLVM 16
        run: |
          sudo apt-get update
          sudo add-apt-repository -y 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main'
          sudo apt-get install -y llvm-16 llvm-16-dev

      - name: Build LLFuzz
        run: |
          ./build.sh || eval $(opam env) && make

      - name: Run test
        run: |
          eval $(opam env) && make test
